---
- name: installing apache2
  hosts: all
  become: yes
  tasks:
    - name: installing apache2
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: yes
    - name: installing php server
      ansible.builtin.apt:
        name:
          - php
          - libapache2-mod-php
          - php-mysql
        state: present
      notify:
        - restart apache2
    - name: copy info.php page
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html/info.php
      notify:
        - restart apache2
  handlers:      
    - name: restart apache2
      ansible.builtin.systemd:
        name: apache2
        state: restarted